#!/usr/bin/env bash
set -euo pipefail
src=${DLSSNR_SOURCE:?Set DLSSNR_SOURCE to the extracted DLSSNR-AMD source root}
out=${1:-build/dlssnr-runtime}
mkdir -p "$out/obj" "$out/generated"
out=$(realpath "$out")
src=$(realpath "$src")
repo=$(cd "$(dirname "$0")/.." && pwd)
cd "$src"
source windows/build/arch/rdna4.sh
python3 windows/build/generate_device_chain.py toolchain/Vulkan-Headers "$out/generated/nr_device_chain_sizes.hpp"
cxx=x86_64-w64-mingw32-g++
common=(-std=c++17 -O2 -DNDEBUG -DNR_BUILD_STAMP='"NRLive-DLSSNR-0.0.4"' -DNR_LIVE_DLSSNR_BRIDGE_EXPORTS
  -Itoolchain/Vulkan-Headers/include -Iwindows/src -Iwindows/src/core -Iwindows/src/pe
  -I"$out/generated" -I"$repo/include")
compile() {
  local name=$1 path=$2
  shift 2
  "$cxx" "${common[@]}" "$@" -c "$path" -o "$out/obj/$name.o"
}
compile runtime windows/src/core/nr_runtime.cpp "${NR_PRODUCT_DEFINES[@]}"
compile native_plan windows/src/core/nr_native_plan.cpp
compile log windows/src/pe/nr_pe_log.cpp
compile crash windows/src/pe/nr_pe_crash.cpp
compile interop windows/src/pe/nr_pe_interop.cpp
compile session windows/src/pe/nr_pe_session.cpp
compile bridge windows/src/pe/nr_pe_bridge.cpp
compile d3d12split windows/src/pe/nr_pe_d3d12split.cpp
compile config windows/src/pe/nr_pe_config.cpp
compile host_api "$repo/src/dlssnr_bridge_api.cpp"
compile vkdevice_stub "$repo/src/dlssnr_vkdevice_stub.cpp"
objs=("$out"/obj/*.o)
ldflags=(-ld3d12 -ldxgi -ldwmapi -lgdi32 -lole32 -ldbghelp -ld3dcompiler -static -static-libgcc -static-libstdc++)
undefined=$({ "$cxx" -shared -o /dev/null "${objs[@]}" "${ldflags[@]}" 2>&1 || true; } |
  grep -o "undefined reference to `vk[A-Za-z0-9_]*'" | sed "s/.*`//; s/'//" | sort -u || true)
{
  echo '// Generated by scripts/build_dlssnr_bridge.sh.'
  echo '    .text'
  for sym in $undefined; do printf '    .globl %s\n%s:\n    jmp *nr_vk_p_%s(%%rip)\n' "$sym" "$sym" "$sym"; done
  echo '    .data'
  for sym in $undefined; do printf '    .globl nr_vk_p_%s\n    .align 8\nnr_vk_p_%s:\n    .quad nr_vk_unresolved\n' "$sym" "$sym"; done
} > "$out/vulkan_lazy.s"
{
  echo '#include <windows.h>'
  echo 'long nr_vk_unresolved(void) { return -3; }'
  for sym in $undefined; do printf 'extern void* nr_vk_p_%s;\n' "$sym"; done
  echo 'void nr_vk_load(void) {'
  echo '  HMODULE m = GetModuleHandleW(L"vulkan-1.dll");'
  echo '  if (!m) m = LoadLibraryW(L"vulkan-1.dll");'
  echo '  if (!m) return;'
  for sym in $undefined; do printf '  { void* p=(void*)GetProcAddress(m,"%s"); if(p) nr_vk_p_%s=p; }\n' "$sym" "$sym"; done
  echo '}'
} > "$out/vulkan_lazy.c"
"$cxx" -c "$out/vulkan_lazy.s" -o "$out/obj/vulkan_lazy_s.o"
x86_64-w64-mingw32-gcc -O2 -c "$out/vulkan_lazy.c" -o "$out/obj/vulkan_lazy_c.o"
"$cxx" -shared -o "$out/NRLiveDlssNrBridge.dll" "${objs[@]}" "$out/obj/vulkan_lazy_s.o" "$out/obj/vulkan_lazy_c.o" "${ldflags[@]}"
test -s "$out/NRLiveDlssNrBridge.dll"
