<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AssemblyName>NRLiveUI</AssemblyName>
    <RootNamespace>NRLiveUI</RootNamespace>
    <ApplicationIcon>img\Icon.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Resource Include="img\Icon.png" />
    <Resource Include="img\Icon.ico" />
  </ItemGroup>
</Project>
